server:
  port: 8089
  
spring:
  application:
    name: auth-service
    
eureka:         
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: false